### ISSUE TITLE
Wrong typing for emit().subscribe()

### ISSUE THREAD

**Issue by raarts** [Redningsselskapet/nestjs-plugins#24]
According to the typings the function passed to subscribe() receives a string parameter but in fact it's an object like this one:

```
pubAck = {
  stream: 'mystream',
  seq: 1,
  duplicate: false
};

```

**Comment by raarts** [comment]
See below. When I hover over the verb `subscribe` WebStorm shows the typing for the subscribe() function: It accepts a function which receives a string parameter and returns void. I printed that parameter and in fact the shape was:

```
{
  stream: string; 
  seq: number;
  duplicate: boolean;
}
```

<img width="1010" alt="Schermafbeelding 2022-03-23 om 8 32 45 PM" src="https://user-images.githubusercontent.com/3168197/159781193-de4f6846-c1a3-442a-a1c4-c7ca3b02e97f.png">

**Comment by kenguru33** [comment]
Thanks for the information. I see what you mean now. 

I have published a new package, @ nestjs-plugins / nestjs-nats-jetstream-transport @ 1.3.0-dev.0, which thinks handles the issue. The emit function will now always return the PubAck class.

Feel free to test and see if it works ok. Very nice with feedback if it seems to work properly.

You will need to make some changes to your code to apply this:
- Replace the NatsJetstreamClientProxy class with the NatsJetsstreamClient in the constructor
- Change emit function as it is now defined as "emit<TInput>(pattern: any, data: TInput): Observable<PubAck>"

Thanks for pointing out the issue :)

**Comment by raarts** [comment]
Yep it works. Thanks!
