### ISSUE TITLE
How to log connection errors and reconnects?

### ISSUE THREAD

**Issue by raarts** [Redningsselskapet/nestjs-plugins#28]
I think I need to listen to connection events as described [here](https://docs.nats.io/using-nats/developer/connecting/reconnect/events). I looked at the code, but could not figure it out. Any suggestions?

**Comment by kenguru33** [comment]
I would think a solution could be to expose the underlying nats connection object.

I'm a little busy right now, but I may look into this later.

Pull requests are always welcome. 🙂

**Comment by kenguru33** [comment]
Hi @raarts 

On the client part (publisher) you can early connect by running the connect() on the client. This will return the underlying nats connection object. e.g.

`@Injectable()
export class AppService {
  constructor(private client: NatsJetStreamClient) {
    client.connect().then(async nc => {
      for await (const s of nc.status()) {
        console.log(s);
        if (s.type == Events.Reconnect) {
          console.log('EventType: ', s.data);
        }
      }
    })     
  }`

On listener part, the nats connection object is not so easy to get accessed. I looking at using a connected hook passed as a connectOption. See the connected_hook branch. What do you think? Will that work for you?

**Comment by kenguru33** [comment]
Merged and published

**Comment by raarts** [comment]
@kenguru33 Yes, I now have connection info in my logs, thanks! 

One note: I got a TypeError when I did not specify connectedHook function:

```TypeScript
TypeError: this.options.connectionOptions.connectedHook is not a function
    at NatsJetStreamServer.listen (/Users/raarts/work/nova/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/server.ts:33:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kenguru33** [comment]
@raarts  Thanks. I have fixed it.
