### ISSUE TITLE
NatsStreamConfig is not exposed, prevents stream configuration

### ISSUE THREAD

**Issue by leopoldodonnell** [Redningsselskapet/nestjs-plugins#35]
When creating a `NatsJetsStreamServer`, the `streamConfig` element does not expose `NatsStreamConfig`. In general the `NatsStreamConfig` type cannot be imported.

**Found in Version:**  1.3.8

### Steps to repeat

1. Setup project using the supplied example from the Readme.md
2. `import { NatsStreamConfig } from '@nestjs-plugins/nestjs-nats-jetstream-transport'`
3. run `yarn build`

```console
yarn build
yarn run v1.22.19
warning ../../package.json: No license field
$ rimraf dist
$ nest build
src/main.ts:7:10 - error TS2305: Module '"@nestjs-plugins/nestjs-nats-jetstream-transport"' has no exported member 'NatsStreamConfig'.

7 import { NatsStreamConfig } from '@nestjs-plugins/nestjs-nats-jetstream-transport'
           ~~~~~~~~~~~~~~~~

Found 1 error(s).

error Command failed with exit code 1.
```

### Workaround:

Copy the code out of the module. Eg: Include the following:

```typescript
mport { StreamConfig, RetentionPolicy } from 'nats';

type $StreamConfig = Pick<
  StreamConfig,
  | 'storage'
  | 'retention'
  | 'discard'
  | 'max_msgs'
  | 'max_msgs_per_subject'
  | 'max_msg_size'
  | 'max_age'
  | 'duplicate_window'
  | 'num_replicas'
>;

export interface NatsStreamConfig extends Partial<$StreamConfig> {
  name: string;
  subjects: string[];
}
```

**Comment by kenguru33** [comment]
The error has now been corrected. 

Thank you for reporting.

**Comment by leopoldodonnell** [comment]
Awesome @kenguru33 - thanks for the rapid fix!
