### ISSUE TITLE
Consumer option ackWait ignored

### ISSUE THREAD

**Issue by Dabada** [Redningsselskapet/nestjs-plugins#40]
**Describe the bug**
Consumer option ackWait ignored. 

Option ackWait  is not set by the ```serverConsumerOptionsBuilder```

https://github.com/Redningsselskapet/nestjs-plugins/blob/f3933fa9d770a2d82ae124c90edfa6ddb81bce36/packages/nestjs-nats-jetstream-transport/src/utils/server-consumer-options-builder.ts#L34

**Comment by kenguru33** [comment]
**Ackwait** option is added to serverConsumerOptionsBuilder
