### ISSUE TITLE
Cannot see effect of manualAck

### ISSUE THREAD

**Issue by subhro-h2** [Redningsselskapet/nestjs-plugins#41]
**Describe the bug**
Cannot see effect of manualAck.

**To Reproduce**
As specified in the docs i am using the below configuration:

strategy: NatsJetStreamServer.

``` 
consumerOptions: {
        ackPolicy: 'All',
        deliverGroup: 'hh-identity-group',
        /*durable: process.env.IDENTITY_QUEUE_GROUP_NAME,*/
        deliverTo: `${process.env.IDENTITY_QUEUE_GROUP_NAME}`,
        **manualAck: true,**
        deliverPolicy: 'New',
        ackWait: 10,
      },

```
In the code of the consumer (@EventPattern) 

`await context.message?.ack()`

If I comment out the above code, in the consumer, still messages are getting processed and getting auto acked.
The consumer code is NOT returning anything.

Seems there is no effect of `manualAck`. 

**Expected behavior**

Should not acknowledge the messages when manulAck is set to true and message is not acknowledged.

**Server:**
 - OS: Ubuntu Linux
 -  "@nestjs/core": "^9.1.4",      "@nestjs/microservices": "^9.1.4",
- "@nestjs-plugins/nestjs-nats-jetstream-transport": "^1.3.11",

**Comment by kenguru33** [comment]
I have tested with code your example, but I am unable to reproduce this. 

By setting manualAck to false, the consumer auto acknowledge the message. With it set to true, the message will be resent until you have the acknowledged the message.

To me everything seems to work as expected.

**Comment by vlad-healthhelper** [comment]
@kenguru33 when you reproduce this issue, how do you start NATS itself? Do you specifically set `NoAck` option?

**Comment by kenguru33** [comment]
No. Just followed the readme
