### ISSUE TITLE
NatsError: CONNECTION_DRAINING at application shutdown

### ISSUE THREAD

**Issue by is-blackhole** [Redningsselskapet/nestjs-plugins#43]
Hello :)

I got uncatchable `NatsError: CONNECTION_DRAINING` exception when shutting down app with app.close()
I need it at my tests to cleanup.

**To Reproduce**
Add to packages/nats-listener/src/main.ts at bootstrap end after `await microService.listen();`:
```
  setTimeout(async() => {
    logger.log("closing app");
    try {
      await app.close();
    } catch (err) {
      logger.error(err);
    }
    logger.log("closed");
  }, 10*1000);
```

**Expected behavior**
App closes, logging "closed";

**Screenshots**
![image](https://user-images.githubusercontent.com/1798383/222134934-84e1f257-49c4-4a6a-9cb0-5a27a5664b33.png)

Looks like app tries to delete consumer via `$JS.API.CONSUMER.DELETE .... ` after drain is called, can you plz take a look?

Thanks

**Comment by kenguru33** [comment]
fixed
