### ISSUE TITLE
request-response hanging on response

### ISSUE THREAD

**Issue by mohantaylor** [Redningsselskapet/nestjs-plugins#46]
Using the NatsJetStreamClientProxy requests are sent correctly but the response is never received by the client.

**To Reproduce**
Setup the example as per the homepage https://www.npmjs.com/package/@nestjs-plugins/nestjs-nats-jetstream-transport.
However, the first issue is that the NatsJetStreamClient is not provided as part of the register in the module so swapped the NatsJetStreamClient for the NatsJetStreamClientProxy which is provided. 

**Expected behavior**
Calling /sum on the service should result in the return value of 6, however, the client hangs.
The console logs from the REST controller and the microservice controller are printed (as per below), but the client never returns.

`% nest start
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [NestFactory] Starting Nest application...
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [InstanceLoader] NatsJetStreamTransport dependencies initialized +6ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [RoutesResolver] AppController {/}: +10ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [RouterExplorer] Mapped {/create, GET} route +0ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [RouterExplorer] Mapped {/update, GET} route +0ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [RouterExplorer] Mapped {/delete, GET} route +0ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [RouterExplorer] Mapped {/sum, GET} route +0ms
[Nest] 2601  - 04/04/2023, 14:44:01     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 2601  - 04/04/2023, 14:44:06     LOG [Server] Stream mystream updated
[Nest] 2601  - 04/04/2023, 14:44:06     LOG [Server] Subscribed to order.updated events
[Nest] 2601  - 04/04/2023, 14:44:06     LOG [Server] Subscribed to order.created events
[Nest] 2601  - 04/04/2023, 14:44:06     LOG [Server] Subscribed to order.deleted events
[Nest] 2601  - 04/04/2023, 14:44:06     LOG [Server] Subscribed to {"cmd":"sum"} messages
[Nest] 2601  - 04/04/2023, 14:44:06     LOG [NestMicroservice] Nest microservice successfully started +0ms
sum controller
message conroller [ 1, 2, 3 ]`

nats 2.9.15
node 18.13.0

"@nestjs-plugins/nestjs-nats-jetstream-transport": "^1.3.14",
"@nestjs/common": "^9.0.0",
"@nestjs/core": "^9.0.0",
"@nestjs/microservices": "^9.3.12",
"@nestjs/platform-express": "^9.0.0",
"nats": "^2.13.1",
"reflect-metadata": "^0.1.13",
"rxjs": "^7.2.0"

**Comment by kenguru33** [comment]
Hi @mohantaylor 

It does not really hang, butt the service does not return anything. It just console logs the result  directly from the service.

If you change the accumalte function in the service example code to something like this it will work:

```javascript
// request - response
  accumulate(payload: number[]) {
    const pattern = { cmd: 'sum' };
    return lastValueFrom(this.client.send<number[]>(pattern, payload));
  }
```
I agree. the example was not very good. Thanks for pointing that out. I will correct it  :)

**Comment by kenguru33** [comment]
@mohantaylor 

Thanks for pointing out the missing provider in the example code in the documentation. I have now corrected it.
