### ISSUE TITLE
subject.replaceAll is not a function

### ISSUE THREAD

**Issue by ebelapia39** [Redningsselskapet/nestjs-plugins#53]
Hello. I found a bug, it’s not clear how to fix it. I went into the source code and corrected it, everything worked. The problem is in the line with replaceAll. It gave an error that subject.replaceAll is not a function

solution

<img width="733" alt="image" src="https://github.com/Redningsselskapet/nestjs-plugins/assets/16219870/f8bc446a-1f0d-41a9-914b-eb7d00badb6b">

**Comment by kenguru33** [comment]
Please see https://github.com/Redningsselskapet/nestjs-plugins/issues/36
